### ISSUE TITLE
Grade for - Forms

### ISSUE THREAD

**Issue by char1129** [char1129/events-calendar#1]
<img width="866" alt="Screen Shot 2020-03-06 at 10 37 54 AM" src="https://user-images.githubusercontent.com/55107755/77490628-c82b4600-6e11-11ea-8203-5da6052d20d6.png">

@muxlowc 😊

**Comment by muxlowc** [comment]
@char1129 thank you so much for reading the online delivery protocol :P

**Comment by char1129** [comment]
> @char1129 thank you so much for reading the online delivery protocol :P
@muxlowc
![3txcjj](https://user-images.githubusercontent.com/55107755/77491244-9c10c480-6e13-11ea-98ec-f2df3fbe1873.jpg)

**Comment by muxlowc** [comment]
@char1129 omg perfect!
